//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_WEB.HRService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMPLOYEE_MODEL", Namespace="http://schemas.datacontract.org/2004/07/HR_PROJECT.Model")]
    [System.SerializableAttribute()]
    public partial class EMPLOYEE_MODEL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> COMMISION_PCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DEPARTMENT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EMPLOYEE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIRST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> HIRE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JOB_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LAST_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MANAGER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHONE_NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SALARYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> COMMISION_PCT {
            get {
                return this.COMMISION_PCTField;
            }
            set {
                if ((this.COMMISION_PCTField.Equals(value) != true)) {
                    this.COMMISION_PCTField = value;
                    this.RaisePropertyChanged("COMMISION_PCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DEPARTMENT_ID {
            get {
                return this.DEPARTMENT_IDField;
            }
            set {
                if ((this.DEPARTMENT_IDField.Equals(value) != true)) {
                    this.DEPARTMENT_IDField = value;
                    this.RaisePropertyChanged("DEPARTMENT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMPLOYEE_ID {
            get {
                return this.EMPLOYEE_IDField;
            }
            set {
                if ((this.EMPLOYEE_IDField.Equals(value) != true)) {
                    this.EMPLOYEE_IDField = value;
                    this.RaisePropertyChanged("EMPLOYEE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIRST_NAME {
            get {
                return this.FIRST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FIRST_NAMEField, value) != true)) {
                    this.FIRST_NAMEField = value;
                    this.RaisePropertyChanged("FIRST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> HIRE_DATE {
            get {
                return this.HIRE_DATEField;
            }
            set {
                if ((this.HIRE_DATEField.Equals(value) != true)) {
                    this.HIRE_DATEField = value;
                    this.RaisePropertyChanged("HIRE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JOB_ID {
            get {
                return this.JOB_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.JOB_IDField, value) != true)) {
                    this.JOB_IDField = value;
                    this.RaisePropertyChanged("JOB_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LAST_NAME {
            get {
                return this.LAST_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.LAST_NAMEField, value) != true)) {
                    this.LAST_NAMEField = value;
                    this.RaisePropertyChanged("LAST_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MANAGER_ID {
            get {
                return this.MANAGER_IDField;
            }
            set {
                if ((this.MANAGER_IDField.Equals(value) != true)) {
                    this.MANAGER_IDField = value;
                    this.RaisePropertyChanged("MANAGER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PHONE_NUMBER {
            get {
                return this.PHONE_NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.PHONE_NUMBERField, value) != true)) {
                    this.PHONE_NUMBERField = value;
                    this.RaisePropertyChanged("PHONE_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SALARY {
            get {
                return this.SALARYField;
            }
            set {
                if ((this.SALARYField.Equals(value) != true)) {
                    this.SALARYField = value;
                    this.RaisePropertyChanged("SALARY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HRService.IHR_SERVICE1")]
    public interface IHR_SERVICE1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/GetAllEmployees", ReplyAction="http://tempuri.org/IHR_SERVICE1/GetAllEmployeesResponse")]
        HR_WEB.HRService.EMPLOYEE_MODEL[] GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/GetAllEmployees", ReplyAction="http://tempuri.org/IHR_SERVICE1/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<HR_WEB.HRService.EMPLOYEE_MODEL[]> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/GetEmployeeById", ReplyAction="http://tempuri.org/IHR_SERVICE1/GetEmployeeByIdResponse")]
        HR_WEB.HRService.EMPLOYEE_MODEL GetEmployeeById(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/GetEmployeeById", ReplyAction="http://tempuri.org/IHR_SERVICE1/GetEmployeeByIdResponse")]
        System.Threading.Tasks.Task<HR_WEB.HRService.EMPLOYEE_MODEL> GetEmployeeByIdAsync(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/InsertEmployee", ReplyAction="http://tempuri.org/IHR_SERVICE1/InsertEmployeeResponse")]
        string InsertEmployee(HR_WEB.HRService.EMPLOYEE_MODEL emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/InsertEmployee", ReplyAction="http://tempuri.org/IHR_SERVICE1/InsertEmployeeResponse")]
        System.Threading.Tasks.Task<string> InsertEmployeeAsync(HR_WEB.HRService.EMPLOYEE_MODEL emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/UpdateEmployee", ReplyAction="http://tempuri.org/IHR_SERVICE1/UpdateEmployeeResponse")]
        string UpdateEmployee(HR_WEB.HRService.EMPLOYEE_MODEL emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/UpdateEmployee", ReplyAction="http://tempuri.org/IHR_SERVICE1/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<string> UpdateEmployeeAsync(HR_WEB.HRService.EMPLOYEE_MODEL emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/DeleteEmployee", ReplyAction="http://tempuri.org/IHR_SERVICE1/DeleteEmployeeResponse")]
        string DeleteEmployee(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHR_SERVICE1/DeleteEmployee", ReplyAction="http://tempuri.org/IHR_SERVICE1/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<string> DeleteEmployeeAsync(int employeeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHR_SERVICE1Channel : HR_WEB.HRService.IHR_SERVICE1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HR_SERVICE1Client : System.ServiceModel.ClientBase<HR_WEB.HRService.IHR_SERVICE1>, HR_WEB.HRService.IHR_SERVICE1 {
        
        public HR_SERVICE1Client() {
        }
        
        public HR_SERVICE1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HR_SERVICE1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HR_SERVICE1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HR_SERVICE1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HR_WEB.HRService.EMPLOYEE_MODEL[] GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<HR_WEB.HRService.EMPLOYEE_MODEL[]> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public HR_WEB.HRService.EMPLOYEE_MODEL GetEmployeeById(int employeeId) {
            return base.Channel.GetEmployeeById(employeeId);
        }
        
        public System.Threading.Tasks.Task<HR_WEB.HRService.EMPLOYEE_MODEL> GetEmployeeByIdAsync(int employeeId) {
            return base.Channel.GetEmployeeByIdAsync(employeeId);
        }
        
        public string InsertEmployee(HR_WEB.HRService.EMPLOYEE_MODEL emp) {
            return base.Channel.InsertEmployee(emp);
        }
        
        public System.Threading.Tasks.Task<string> InsertEmployeeAsync(HR_WEB.HRService.EMPLOYEE_MODEL emp) {
            return base.Channel.InsertEmployeeAsync(emp);
        }
        
        public string UpdateEmployee(HR_WEB.HRService.EMPLOYEE_MODEL emp) {
            return base.Channel.UpdateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task<string> UpdateEmployeeAsync(HR_WEB.HRService.EMPLOYEE_MODEL emp) {
            return base.Channel.UpdateEmployeeAsync(emp);
        }
        
        public string DeleteEmployee(int employeeId) {
            return base.Channel.DeleteEmployee(employeeId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteEmployeeAsync(int employeeId) {
            return base.Channel.DeleteEmployeeAsync(employeeId);
        }
    }
}
